### ISSUE TITLE
Getting backslash in the filename

### ISSUE THREAD

**Issue by RemiHin** [vildanbina/laravel-model-json#6]
When running `php artisan model:export Track --except-fields=coordinates --filename=tracks` 

the outputted filename is `\tracks.json` which makes the file unaccessable

I've tried every option i could think of, but cant seem to fix it

**Comment by vildanbina** [comment]
I was unable to reproduce this issue on my end. Could you please provide details about the operating system you're using? Also, it might be helpful to check if any Laravel configuration settings are contributing to the problem. To address potential cross-platform compatibility issues, I've released version 2.1, where the hardcoded backslash has been replaced with `DIRECTORY_SEPARATOR`.

**Comment by RemiHin** [comment]
fantastic, this fixed it.
FYI, im on a M2 macbook pro
